openapi: 3.0.3
info:
  title: Clickster
  description: |-
    An easy to use event storage api
  version: 1.0.0
tags:
  - name: Event
    description: Everything to manage events
paths:
  /api/v1/events:
    get:
      tags:
        - Event
      summary: List and query events
      description: |-
        An endpoint that allows you to list all events and query for events meeting
        certain criteria
      parameters:
        - in: query
          name: url
          schema:
            type: string
            format: url
            example: "https://example.com"
          required: false
        - in: query
          name: event_type
          example: 'click'
          schema:
            $ref: "#/components/schemas/EventType"
          required: false
        - in: query
          name: from
          schema:
            type: string
            format: ISO8601
            example: "2022-08-29T06:46:34.650Z"
          required: false
        - in: query
          name: to
          schema:
            type: string
            format: ISO8601
            example: "2022-08-29T06:46:34.650Z"
          required: false
      responses:
        '200':
          description: Successfull operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
        '400':
          description: Bad query paramters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GenericErrorMessage'

    post:
      tags:
        - Event
      summary: Create new event
      description: Create a new event by specifying its type as well as the URL
      requestBody:
        description: Payload of the new event
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEventRequestBody'
        required: true
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'

        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericErrorMessage'


components:
  schemas:
    EventType:
      type: string
      enum:
        - click
        - page_view
    CreateEventRequestBody:
      type: object
      properties:
        event_type:
          $ref: "#/components/schemas/EventType"
        url:
          type: string
          format: url
          example: "https://example.com"
    Event:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        event_type:
          $ref: "#/components/schemas/EventType"
        url:
          type: string
          format: url
          example: "https://example.com"
        created_at:
          type: string
          format: ISO8601
          example: "2022-08-29T06:46:34.650Z"
        updated_at:
          type: string
          format: ISO8601
          example: "2022-08-29T06:46:34.650Z"
    GenericErrorMessage:
      type: object
      additionalProperties:
          type: array
          items:
            type: string
          description: "An array of error messages for the field specified by the key"
      example:
        "event_type": ["can't be blank"]
